# Generated by Django 5.1.2 on 2024-10-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_variation_variation_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_value",
            field=models.CharField(max_length=100),
        ),
    ]
