# Generated by Django 5.1.2 on 2024-10-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("product", "0004_alter_variation_variation_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="product.variation"),
        ),
    ]
