# Generated by Django 5.1.2 on 2024-10-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_variation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher_name", models.CharField(max_length=100)),
                ("voucher_discount", models.IntegerField()),
                ("voucher_validity", models.CharField(max_length=100)),
                ("voucher_status", models.BooleanField(default=True)),
            ],
        ),
    ]
