# Generated by Django 5.1.2 on 2024-10-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_voucher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="voucher_validity",
            field=models.DateTimeField(),
        ),
    ]
