# Generated by Django 5.1.2 on 2024-10-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_voucher_voucher_validity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="voucher_validity",
            field=models.DateField(),
        ),
    ]
